# Number of quests that can be in progress at a time
questLimit: 5

# When a quest is completed a leader board message is broadcast. Chose the maximum number of players to be displayed.
# If this is set to 0 then the leader board message will be omitted.
leaderBoardSize: 5

# MUST BE IN ALL CAPS!
# See color options here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
barColor: "GREEN"

disableBossBar: true

Quests:

  TestQuest: # Quest identifier can be whatever you'd like as long as it's unique
    displayName: "&c&lZombie and Pig Slayer"
    type: mobkill # required, see type list for available types
    entities: # This is an optional parameter, if it doesn't exist the quest will count all mob kills. entity reference: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
      - Zombie
      - Pig
      - Pig_Zombie
    description: "&fKill 5 zombies as fast as you can!"
    goal: 5 # The goal is the amount of the task to be completed
    rewards:
      experience: 100
      money: 1000 # You must have Vault and an Economy plugin installed for this to work
      items:
        - material: DIAMOND_SWORD
          amount: 1
          displayName: "&bPowerful Diamond Sword"
        - material: APPLE
          amount: 12
          displayName: "&capples"


  GuiQuest:
    displayName: "&l&aGather 10 Potatoes"
    type: donate
    materials:
      - POTATO
      - APPLE
    description: "&Donate 10 potatoes using the command /cq donate to complete the quest!"
    timeToComplete: 60
    goal: 10
    rewards:
      experience: 100
      money: 1000 # You must have Vault and an Economy plugin installed for this to work
      commands:
        - give player stick 15 # player will be replaced with the name of the player receiving the reward.
      items:
        - material: DIAMOND_SWORD
          amount: 1
          displayName: "&bPowerful Diamond Sword"
        - material: APPLE
          amount: 12
          displayName: "&capples"

  DiamondHunter:
    displayName: "&b&lDiamond Hunter"
    type: blockbreak
    materials:
      - DIAMOND_ORE
    description: "&fCollect 100 diamonds!"
    goal: 100
    rewards:
      money: 100.0

  WolfQuest:
    displayName: Wolf Lover
    type: tame
    description: Make some friends
    goal: 5
    rewards:
      money: 100.0

  Fishing:
    displayName: Catch Fish
    type: catchfish
    description: Catch 3 fish!
    goal: 3
    rewards:
      experience: 100

  SheepShear:
    displayName: Shear Sheep
    type: shear
    description: Let's get that wool baby
    goal: 1000
    rewards:
      experience: 100

  PlantTree:
    displayName: Save the Planet
    type: blockplace
    description: Place 10 oak or acacia trees to save the world!
    goal: 10
    materials:
      - OAK_SAPLING
      - ACACIA_SAPLING
