# Number of quests that can be in progress at a time
questLimit: 5

# When a quest is completed a leader board message is broadcast. Chose the maximum number of players to be displayed.
# If this is set to 0 then the leader board message will be omitted.
leaderBoardSize: 5

# MUST BE IN ALL CAPS!
# See color options here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
barColor: "GREEN"

disableBossBar: true

Quests:
#    PlantTree:
#        displayName: Save the Planet
#        type: blockplace
#        description: Place 10 oak or acacia trees to save the world!
#        goal: 10
#        materials:
#          - OAK_SAPLING
#          - ACACIA_SAPLING

