# Number of quests that can be in progress at a time
questLimit: 5

# When a quest is completed a leader board message is broadcast. Chose the maximum number of players to be displayed.
# If this is set to 0 then the leader board message will be omitted.
leaderBoardSize: 5

# See color options here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
barColor: "GREEN"

disableBossBar: false

# If enabled, blockbreak quests will not be able to break the same item multiple
# times in a row.
disableDuplicateBreaks: false

# If enabled, blockplace quests will not be able to place the same item multiple
# times in a row.
disableDuplicatePlaces: false

# Material used in the donate quest menu.
donateMenuItem: OBSIDIAN

Quests:
    TestQuest: # Quest identifier can be whatever you'd like as long as it's unique
        displayName: "&cZombie and Pig Slayer"
        displayItem: ZOMBIE_HEAD # optional parameter to set the item used in GUIs for a given quest
        worlds: # this parameter is optional, if included the quest will only occur in the specified worlds
            - world
        objectives: # at least one objective is required, each quest can have infinite objectives
            - type: mobkill ## required, see type list for available types
              goal: 10 # The goal is the amount of the task to be completed
              entities: # This is an optional parameter, if it doesn't exist the quest will count ALL mob kills. entity reference: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
                  - Zombie
                  - Pig
                  - ZOMBIFIED_PIGLIN
              description: "Zombies & Pigs" # A short description of the objective used in the GUI
            - type: mobkill
              goal: 5
              entities:
                  - Skeleton
              description: Skeletons
        description: Kill 100 zombies and pigs!
        questDuration: 1d # The quest will last for 1 day or until the goal is reached, whichever comes first
        rewards:
            rankedRewards:
                "1": # The key is the rank of the player so this reward will be given to the player who contributed the most
                    experience: 100
                    items:
                        - material: diamond_sword
                          amount: 1
                          displayName: "&bPowerful Diamond Sword"
                "2":
                    experience: 50
                    items:
                        - material: iron_sword
                          amount: 1
                          displayName: "&7Iron Sword"
                "*": # This is a wildcard, this reward will apply to all other players who participated in the quest and didn't get a ranked reward
                    experience: 25
                    items:
                        - material: stone_sword
                          amount: 1
                          displayName: "&8Stone Sword"
