name: CommunityQuests
version: 1.0
author: wonka01
main: me.wonka01.ServerQuests.ServerQuests
api-version: 1.13

commands:
  cq:
    usage:
    description: Commands for Community Quests Plugin

permissions:
  communityquests.start:
    description: The ability to start server events
    default: op
  communityquests.stop:
    description: The ability to stop an event
    default: op
  communityquests.reload:
    description: Can reload the plugins configurations
    default: op
  communityquests.view:
    description: Can view all active quests for the server
    default: true
  communityquests.showmessages:
    description: If true the player will receive a message when they contribute to the quest
    default: true
  communityquests.bossbar.hide:
    description: The player will not be shown the boss bar by default
    default: false